### ISSUE TITLE
Order page redesign

### ISSUE THREAD

**Issue by brianbest** [robmyers82/pizzagoManagerTablet#27]
Redesign so that all content stacks. Store info should only be available if the use taps on it to see.

**Comment by robmyers82** [comment]
As per issue #19:

Here is a breakdown of the page issues (Can provide screenshots):

Active/Completed Orders links are not side to side on Samsung, and instead the completed orders link is below the Active link
'Displaying Active Orders' paragraph is line-breaking after "Active", even though there is plenty of whitespace in between it and the "active, completed" links
Orders have a similar line-break issue as title
